### ISSUE TITLE
StyleClassedTextArea scroll bar

### ISSUE THREAD

**Issue by Ppsoft1991** [FXMisc/RichTextFX#1016]
I used StyleClassedTextArea to show some Text.

javafx textarea will auto create scroll bar
![image](https://user-images.githubusercontent.com/18442117/120363770-1e154b00-c33f-11eb-9161-9b859d445b0f.png)

StyleClassedTextArea can't auto create scroll bar

![image](https://user-images.githubusercontent.com/18442117/120364024-587ee800-c33f-11eb-9b78-9426578efec5.png)

**Comment by Jugen** [comment]
Wrap the StyleClassedTextArea in a `org.fxmisc.flowless.VirtualizedScrollPane`:
```java
var scroll = new VirtualizedScrollPane( area );
```
or in FXML
```xml
<VirtualizedScrollPane>
    <content>
        <StyledClassedTextArea .... />
    </content>
</VirtualizedScrollPane>
```

**Comment by Ppsoft1991** [comment]
![image](https://user-images.githubusercontent.com/18442117/120410596-dbc32c80-c385-11eb-9a1d-9275be203149.png)
I tried and it doesn't works

**Comment by Ppsoft1991** [comment]
It works! good project!

**Comment by rinavolu** [comment]
Hey @Ppsoft1991 ,
Need to apply some stylings to scrollbar , I'm using **VirtualizedScrollPane** . Can you help me ?

**Comment by Jugen** [comment]
Sorry for the late reply ....

Use `.virtualized-scroll-pane .scroll-bar` or `.virtualized-scroll-pane > .scroll-bar`

Try something like the following:

```css
/* The main scrollbar track */
.virtualized-scroll-pane .scroll-bar:horizontal .track,
.virtualized-scroll-pane .scroll-bar:vertical .track{
    -fx-background-color :transparent;
    -fx-border-color :transparent;
    -fx-background-radius : 0.0em;
    -fx-border-radius :2.0em;
}

/* Horizontal increment and decrement buttons */
.virtualized-scroll-pane .scroll-bar:horizontal .increment-button ,
.virtualized-scroll-pane .scroll-bar:horizontal .decrement-button {
    -fx-background-color :transparent;
    -fx-background-radius : 0.0em;
    -fx-padding :0.0 0.0 10.0 0.0;

}

/* Vertical increment and decrement buttons */
.virtualized-scroll-pane .scroll-bar:vertical .increment-button ,
.virtualized-scroll-pane .scroll-bar:vertical .decrement-button {
    -fx-background-color :transparent;
    -fx-background-radius : 0.0em;
    -fx-padding :0.0 10.0 0.0 0.0;

}

/* Horizontal increment and decrement arrows */
.virtualized-scroll-pane .scroll-bar:horizontal .increment-arrow,
.virtualized-scroll-pane .scroll-bar:horizontal .decrement-arrow{
    -fx-shape : " ";    
    -fx-padding :0.15em 0.0;
}

/* Vertical increment and decrement arrows */
.virtualized-scroll-pane .scroll-bar:vertical .increment-arrow,
.virtualized-scroll-pane .scroll-bar:vertical .decrement-arrow{
    -fx-shape : " ";    
    -fx-padding :0.0 0.15em;
}

/* Scrollbar thumb */
.virtualized-scroll-pane .scroll-bar:horizontal .thumb,
.virtualized-scroll-pane .scroll-bar:vertical .thumb {
    -fx-background-color :derive(black,90.0%);
    -fx-background-insets : 2.0, 0.0, 0.0;
    -fx-background-radius : 2.0em;
}

/* Scrollbar thumb hover and pressed */
.virtualized-scroll-pane .scroll-bar:horizontal .thumb:hover,
.virtualized-scroll-pane .scroll-bar:horizontal .thumb:pressed,
.virtualized-scroll-pane .scroll-bar:vertical .thumb:pressed,
.virtualized-scroll-pane .scroll-bar:vertical .thumb:hover {
    -fx-background-color :derive(#4D4C4F,10.0%);
    -fx-background-insets : 2.0, 0.0, 0.0;
    -fx-background-radius : 2.0em;
}
```
