### ISSUE TITLE
minWidth not working on paragraph graphic node

### ISSUE THREAD

**Issue by RationalityFrontline** [FXMisc/RichTextFX#1124]
## Expected Behavior

When using LineNumberFactory with the following css, the line number label should have minimum width of 25.
```css
.code-area .lineno {
    -fx-min-width: 25;
    -fx-max-width: infinity;
    -fx-font-size: 12;
}
```

## Actual Behavior

When line number is under 10, its width is less than 25.

## Environment info:

- RichTextFX Version: 0.10.9
- Operating System: Window 10
- Java version: 17
