### ISSUE TITLE
how to set line-spacing

### ISSUE THREAD

**Issue by impactCn** [FXMisc/RichTextFX#1190]
- [ Y ] Already google
 - [ Y ] Already chatgpt
 - [ Y ] Already check issue
 - [ Y ] Already stackoverflow
<hr>

## Expected Behavior

Line-spacing to bigger

## Actual Behavior

![image](https://github.com/FXMisc/RichTextFX/assets/35489877/318c485b-56c3-4e24-95bf-ac09a5f61148)

no change

## Reproducible Demo

Provide a demo that maintainers of this project can copy, paste, and run to reproduce it immediately.

Use the following template to get started.
````java
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Example");

        CodeArea codeArea = new CodeArea();

        Scene scene = new Scene(codeArea, 400, 300);
        scene.getStylesheets().add(getClass().getResource("styles.css").toExternalForm());
        primaryStage.setScene(scene);
        primaryStage.show();

    }
````
styles
```css
.paragraph-box {
    -fx-line-spacing: 40;
}

.code-area {

    -fx-line-spacing: 35;
}

.text {
    -fx-line-spacing: 5;
}

.paragraph-text {
    -fx-line-spacing: 20;
}


.paragraph-box {
    -fx-padding: 30 30 30 30;
}
```
## Environment info:

- RichTextFX Version: 0.11.1
- Operating System: windows 10
- Java version: 17

<hr>

How should I modify line-spacing?

**Comment by Jugen** [comment]
See [RichTextFX CSS Reference Guide](https://github.com/FXMisc/RichTextFX/wiki/RichTextFX-CSS-Reference-Guide), and try:
```css
.text-flow {
    -fx-line-spacing: <number>;
}
```

**Comment by impactCn** [comment]
Hi jugen.
![image](https://github.com/FXMisc/RichTextFX/assets/35489877/75e8f95b-a817-4508-afa9-f584ec6ef34f)
seem no change.

**Comment by Jugen** [comment]
The problem seems to be that the "_styled-text-area.css_" file inside the richtextfx jar file overrides any user css settings.
I've removed the default linespacing in the attached [richtextfx-fat-0.11.1.zip](https://github.com/FXMisc/RichTextFX/files/12891151/richtextfx-fat-0.11.1.zip) file (just rename zip to jar).

Then use the following in your CSS file and it should work:
```css
.paragraph-text {
    -fx-line-spacing: 20;
}
```

**Comment by Jugen** [comment]
Here's a better work-around:
```java
codeArea.setId( "myarea" );
```
```css
#myarea .paragraph-text {
    -fx-line-spacing: 10;
}
```

**Explanation**: CSS is applied from least specific to most specific, with the most specific selector overriding the lesser.
Since the default CSS in "_styled-text-area.css_" for **-fx-line-spacing** is already highly specified as `.styled-text-area .paragraph-box .paragraph-text` we need to use the Node Id specifier to override it.
