### ISSUE TITLE
Question: How to set selection color via code or CSS?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1215]
I want to set selection color (currently blue) for example to yellow. Could anyone say how to do it via CSS? If it is not possible via CSS, how to do it programmatically?

**Comment by Jugen** [comment]
Try the following:
```css
.main-selection {
    -fx-fill: green;
}
```
