### ISSUE TITLE
Question: How to set background color for current line/paragraph using CSS?

### ISSUE THREAD

**Issue by PavelTurk** [FXMisc/RichTextFX#1222]
Could anyone say, how to set background color for current line/paragraph? I mean something like this:
![Screenshot from 2024-05-09 18-43-09](https://github.com/FXMisc/RichTextFX/assets/10261361/6ce500c4-0a7f-41fe-bda1-109d9b0c165c)

It is possible to do via CSS?

**Comment by Jugen** [comment]
```css
.styled-text-area .line-highlighter { -fx-fill: ivory; }
```

**Comment by Jugen** [comment]
Try this instead then:
```css
.paragraph-box:has-caret {
    -fx-background-color: yellow;
}
```
Note that `-fx-fill` won't work.
