### ISSUE TITLE
Question: Getting font size of the CodeArea

### ISSUE THREAD

**Issue by KoblizekXD** [FXMisc/RichTextFX#1228]
Hello, I'm currently building an application which requires me to use CodeArea and I would like to implement mouse wheel scrolling zoom, therefore I need to get a actualy font size and increase/decrease it. I didn't find any method to get that, as `getFont()` doesn't seem to exist. From what I've yet understood, the font size value can be stored in CSS like this:
```css
.styled-text-area .text {
    -fx-font-size: 24pt;
}
```  
But I'm not really sure how could I retrieve it! I will be grateful for any response! Thanks!
