### ISSUE TITLE
Question: styling VirtualizedScrollPane

### ISSUE THREAD

**Issue by iAmGio** [FXMisc/RichTextFX#682]
I need to style a `VirtualizedScrollPane`. I tried:
```css
.virtualized-scroll-pane {
    -fx-background-color: #4b5660
}

.virtualized-scroll-pane > .viewport {
    -fx-background-color: #a9a9a9
}
```
But it seems I'm doing something wrong since nothing changes.
How do I style these parts (see image)?
![Scroll pane image](https://i.imgur.com/f6iHWJR.png)
