### ISSUE TITLE
Adding extra padding to a cell/element

### ISSUE THREAD

**Issue by MrChebik** [FXMisc/RichTextFX#772]
Hi, if  I understand the principle of text construction correctly, then each symbol is a separate element. Have `CodeArea` ability to change padding to a cell (element)?
For example, a cell stores a character of a specific font, and add padding at the top/bottom.

A screenshot, it might help to understand if I didn't make myself clear.
Above what is now, and below what was. Now, the typeface is too dense, and has little distance from each paragraph.
In the example below, I was just adding padding to `CodeArea`: `-fx-padding: 1 2 3 2;`. Is it possible to get to the element itself that holds the symbol by `css` class?

![untitled](https://user-images.githubusercontent.com/11232501/44458879-3f826d80-a610-11e8-9232-9fd14ff58fb5.png)

--
I create `Autocomplete` element, which contain many variations. To reduce memory usage (by 75-100mb), I use single `CodeArea` element, to store options.

**Comment by MrChebik** [comment]
I found `paragraph-box` class:
```css
.paragraph-box {
    -fx-padding: 1 2 3 2;
}

.paragraph-box:has-caret {
    -fx-background-color: #e69500;
}
```
