### ISSUE TITLE
I wanna set only color of text in StyleClassedTextArea but color of line numbers of LineNumberFactory changing too.

### ISSUE THREAD

**Issue by Pledix** [FXMisc/RichTextFX#808]
I am using StyleClassedTextArea via LineNumberFactory.
I wanna set only color of text in StyleClassedTextArea but color of line numbers of LineNumberFactory changing too.

````css
.styled-text-area .text {
    -fx-fill: red;
}

.lineno {
    -fx-background-color: #282C34;
    -fx-font: 13px "Consolas";
    -fx-text-fill: #4B5262;
}
````
