### ISSUE TITLE
Setting CodeArea font via css not working

### ISSUE THREAD

**Issue by lynxprotocol** [FXMisc/RichTextFX#911]
Setting the font family for CodeArea not working as nice after updating to version 0.10.4. The CSS code is as below:
`-fx-font-family: fontName;`
The font `fontName` has already been loaded by the class.
I'm still using the version of Java(8) I used with the previous version of RichtextFX

**Comment by Jugen** [comment]
Try using the following in the meantime and see if this works for you:

```css
.code-area .text {
    -fx-font-family: fontName;
}
```
